
package ViewPeaje;

//Importamos las clases y librerias 

import controllerPeaje.ControladorPeaje;
import javax.swing.JOptionPane;
import sistemapeaje.Carro;
import java.awt.event.*;
import sistemapeaje.Camion;
import sistemapeaje.Moto;
import sistemapeaje.Peaje;
/**
 *
 * @author Carlos Ron
 * @Fecha: 27/06/2025
 * @descripcion: Creare unos botones el cual aplate el usurio pedira el numero de placa y 
 * en caso de camion tambien el numero de jes , con una opcion de guardar los datos en archivo Json  y 
 * otro boton para limpiar el programa 
 */
public class PeajeFrame extends javax.swing.JFrame {
    //creamos una variable llamada peaje 
    private Peaje peaje;

    /**
     * Creates new form PeajeFrame
     */
    public PeajeFrame() {
        initComponents();
        //Creamos el nombre y al departamento al cual pertenece 
        peaje = new Peaje("Peaje de Oyacoto", "Quito");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonCarro = new javax.swing.JButton();
        totalPeaje = new javax.swing.JLabel();
        botonMoto = new javax.swing.JButton();
        botonCamion = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel1.setText("Sistema de peaje ");

        botonCarro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCarro.setText("Carro");
        botonCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarroActionPerformed(evt);
            }
        });

        totalPeaje.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalPeaje.setText("Total peaje: 0");

        botonMoto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonMoto.setText("Moto");
        botonMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMotoActionPerformed(evt);
            }
        });

        botonCamion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCamion.setText("Camion");
        botonCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCamionActionPerformed(evt);
            }
        });

        botonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("Elije el tipo de vehiculo:");

        botonSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(botonCarro)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(botonMoto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addComponent(botonCamion)))
                        .addGap(45, 45, 45))))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(totalPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(totalPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarroActionPerformed
        // TODO add your handling code here:
        //creamos una variable para que ingrese la matricula 
        String placa = JOptionPane.showInputDialog(null, "Ingrese la matricula del carro"); 
        //Verificamos si el usuario ingresa un valor no nulo
        if(placa != null && !placa.trim().isEmpty()){
        //Añadimos el vehiculo usando la matricula ingresada
            peaje.añadirVehiculo(new Carro(placa.trim()));  
            //Mostramos el total de peaje acumulado
            totalPeaje.setText("Total peaje: " + peaje.getTotalPeaje());  
            
        }
    }//GEN-LAST:event_botonCarroActionPerformed

    private void botonMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMotoActionPerformed
        // TODO add your handling code here:
        //creamos una variable para que ingrese la matricula
        String placa = JOptionPane.showInputDialog(null, "Ingrese la matricula de la moto");
        //Verificamos si el usuario ingresa un valor no nulo
        if(placa != null && !placa.trim().isEmpty()){
            //Añadimos el vehiculo usando la matricula ingresada
            peaje.añadirVehiculo(new Moto(placa.trim()));
            //Mostramos el total de peaje acumulado
            totalPeaje.setText("Total peaje: " + peaje.getTotalPeaje());
            
        }
    }//GEN-LAST:event_botonMotoActionPerformed

    private void botonCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCamionActionPerformed
        // TODO add your handling code here:
        //creamos una variable para que ingrese la matricula
        String  placa = JOptionPane.showInputDialog(null, "Ingrese la matricula del camion: ");
        //Verificamos si el usuario ingresa un valor no nulo
        if(placa != null && !placa.trim().isEmpty()){
            //Creamos una variable para que ingrese los ejes 
            String ejesStr = JOptionPane.showInputDialog(null, "Ingrese el numero de ejes: ");
            try{
                //Creamos una variable que guarde el valor entero de ejesStr
                int ejes = Integer.parseInt(ejesStr);
                //Añadimos el vehiculo usando la matricula ingresada y los ejes ingresados
                peaje.añadirVehiculo(new Camion(placa.trim(), ejes));
                //Mostramos el total de peaje acumulado
                totalPeaje.setText("Total peaje: " + peaje.getTotalPeaje());
                
            }catch(NumberFormatException ex){
                
                //Si hay un error presentamos un mensaje 
                JOptionPane.showMessageDialog(null, "Numero de ejes invalidos");
                
            }
        }
        
    }//GEN-LAST:event_botonCamionActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
        //Llamamos a la clase Controlador para guardar el archivo
        ControladorPeaje.guardar(peaje);
        //Presentamos un mesaje si se guardo el archivo
        JOptionPane.showMessageDialog(this, "Datos Guardados");
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        // TODO add your handling code here:
        //Creamos una variable local  con un valor de 0
        int contador = 0;
        //hacemos que totalPeaje improma el valor de 0
        totalPeaje.setText("Total Peaje: " + contador);
                
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeajeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeajeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeajeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeajeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeajeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCamion;
    private javax.swing.JButton botonCarro;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonMoto;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel totalPeaje;
    // End of variables declaration//GEN-END:variables
}
